pipeline:
  clone:
    tags: true
    image: plugins/git
  check-copyright:
    image: hub.docker.hpecorp.net/arta/copyright:v0.3.4
    commands:
      - check-copyright.sh
    when:
      event: [pull_request]

  publish-container:
    group: deliver
    image: hub.docker.hpecorp.net/picasso/containerize:v1.6.2
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    environment:
      - PUBLISH=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - containerize.sh
    when:
      # Tags will publish, PRs will just build
      event: [ pull_request, tag ]

  publish-container:
    group: deliver
    image: hub.docker.hpecorp.net/picasso/containerize:v1.6.2
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    environment:
      - PUBLISH=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - containerize.sh
    when:
      branch: master
      event: push

